Update justfile and CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,25 +22,15 @@ jobs:
       - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
         uses: Swatinem/rust-cache@v2
       - uses: taiki-e/install-action@v2
-        with: { tool: 'just,cargo-llvm-cov' }
+        with: { tool: just }
       - if: github.event_name == 'release'
         name: Ensure this crate has not yet been published (on release)
         run: just check-if-published
-      - run: RUST_BACKTRACE=1 just -v ci-test
+      - run: just ci-test
       - name: Check semver
         uses: obi1kenobi/cargo-semver-checks-action@v2
-      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
-        name: Generate code coverage
-        run: just ci-coverage
-      - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
-        name: Upload coverage to Codecov
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: target/llvm-cov/codecov.info
-          fail_ci_if_error: true
 
-  msrv:
+  test-msrv:
     name: Test MSRV
     runs-on: ubuntu-latest
     steps:
@@ -57,10 +47,32 @@ jobs:
         with:
           toolchain: ${{ steps.msrv.outputs.value }}
           components: rustfmt
-      - run: just -v ci-test-msrv
+      - run: just ci-test-msrv
+        env:
+          # Ignore warnings in MSRV. Sadly, this cannot be done inside `just ci-test-msrv`
+          CI: ''
+
+  coverage:
+    name: Code Coverage
+    if: github.event_name != 'release'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: 'just,cargo-llvm-cov' }
+      - name: Generate code coverage
+        run: just ci-coverage
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v5
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: target/llvm-cov/codecov.info
+          fail_ci_if_error: true
 
   build:
     name: Build ${{ matrix.target }}
+    needs: [ test ]
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -155,6 +167,7 @@ jobs:
 
   cross-build:
     name: Cross-build
+    needs: [ test ]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
@@ -182,10 +195,20 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  publish:
+  # This job checks if any of the previous jobs failed or were canceled.
+  # This approach also allows some jobs to be skipped if they are not needed.
+  ci-passed:
+    if: always()
+    needs: [ test, test-msrv, coverage, build, cross-build ]
+    runs-on: ubuntu-latest
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: exit 1
+
+  release:
     if: startsWith(github.ref, 'refs/tags/')
     name: Publish to crates.io
-    needs: [ test, msrv, build, cross-build ]
+    needs: [ ci-passed ]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
